services:
  docs:
    image: listen_hear_local_docs
    container_name: listen_hear_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./listen_hear:/app/listen_hear:z
    ports:
      - '9000:9000'
    command: /start-docs
