volumes:
  listen_hear_local_postgres_data: {}
  listen_hear_local_postgres_data_backups: {}
  listen_hear_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: listen_hear_local_django
    container_name: listen_hear_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: listen_hear_production_postgres
    container_name: listen_hear_local_postgres
    volumes:
      - listen_hear_local_postgres_data:/var/lib/postgresql/data
      - listen_hear_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: listen_hear_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:8.4
    container_name: listen_hear_local_redis
    volumes:
      - listen_hear_local_redis_data:/data

  celeryworker:
    <<: *django
    image: listen_hear_local_celeryworker
    container_name: listen_hear_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: listen_hear_local_celerybeat
    container_name: listen_hear_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: listen_hear_local_flower
    container_name: listen_hear_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: listen_hear_local_node
    container_name: listen_hear_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
